name: Build Release Asset

on:
  workflow_dispatch:
  #release:
  #  types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      commit_secret: ${{ secrets.commit_secret }}
      github_token: ${{ secrets.github_token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo, sqlite
          tools: composer, npm

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-scripts --no-progress --no-dev --optimize-autoloader

      - name: Create Release Build
        run: |
          # Remove unnecessary files
          rm -rf .git .github tests
          rm -f .gitattributes .gitignore phpunit.xml
          
          # Create zip file
          zip -r release.zip .

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.commit_secret }}"
          draft: false
          prerelease: false
          title: "Latest Release"
          automatic_release_tag: "v0.9.0"
          files: |
            ${{ github.workspace }}/release-v0_9_0.zip
