name: Build Release Asset

on:
  workflow_dispatch:
  #release:
  #  types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    #env:
    #  commit_secret: ${{ secrets.commit_secret }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: Create Release Build
        run: |
          # Remove unnecessary files
          rm -rf .git .github tests
          rm -f .gitattributes .gitignore phpunit.xml
          
          # Create zip file
          zip -r release.zip .